name: Pull request
on: pull_request

jobs:
  commitsar:
    runs-on: ubuntu-latest
    name: Verify commit messages
    steps:
      - uses: actions/checkout@v1
      - name: Run commitsar
        uses: docker://aevea/commitsar@sha256:4e1d112924e8cffc829c39291f26e11d45539b40204f287647cac34bbfc4654c
